---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	scraper(scraper)
	classifier(classifier)
	optimizer(optimizer)
	sheets_reader(sheets_reader)
	sheets_writer(sheets_writer)
	__end__([<p>__end__</p>]):::last
	__start__ --> sheets_reader;
	classifier -.-> optimizer;
	classifier -.-> sheets_writer;
	optimizer --> sheets_writer;
	scraper -.-> classifier;
	scraper -.-> sheets_writer;
	sheets_reader -.-> scraper;
	sheets_reader -.-> sheets_writer;
	sheets_writer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

